<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">

    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">

    <title>Cafetería App</title>

    <link rel="stylesheet"
          href="<?= BASE_URL ?>view/css/style.css">
</head>

<body>

<header>

    <h1>Cafetería App</h1>

    <nav>

        <a href="<?= BASE_URL ?>categorias">
            Categorías
        </a>

        <?php if(isset($_SESSION['USERNAME'])): ?>

            <span>
                Hola, <?= htmlspecialchars($_SESSION['USERNAME']) ?>
            </span>

            <a href="<?= BASE_URL ?>logout">
                Cerrar Sesión
            </a>

        <?php else: ?>

            <a href="<?= BASE_URL ?>login">
                Iniciar Sesión
            </a>

        <?php endif; ?>

    </nav>

</header>