<?php require './view/templates/header.phtml'; ?>

<h1>Editar producto</h1>

<form action="<?= BASE_URL ?>editarProducto/<?= $producto->id_producto ?>"
      method="POST">

    <input type="text"
           name="nombre"
           value="<?= $producto->nombre ?>">

    <input type="text"
           name="descripcion"
           value="<?= $producto->descripcion ?>">

    <input type="number"
           name="precio"
           value="<?= $producto->precio ?>">

    <button type="submit">
        Guardar
    </button>

</form>

<?php require './view/templates/footer.phtml'; ?>